# Generated by Django 4.0.4 on 2022-06-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_alumno_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='nacimiento',
        ),
    ]
